//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public Accounts()
        {
            this.Characters = new HashSet<Characters>();
        }
    
        public int acc_id { get; set; }
        public string acc_log { get; set; }
        public string acc_pass { get; set; }
        public int right_id { get; set; }
    
        public virtual Rights Rights { get; set; }
        public virtual ICollection<Characters> Characters { get; set; }
    }
}
