//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bag
    {
        public int char_id { get; set; }
        public int item_id { get; set; }
        public int bag_id { get; set; }
    
        public virtual Characters Characters { get; set; }
        public virtual Items Items { get; set; }
    }
}
