//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colors
    {
        public Colors()
        {
            this.Races = new HashSet<Races>();
        }
    
        public int col_id { get; set; }
        public string col_n { get; set; }
    
        public virtual ICollection<Races> Races { get; set; }
    }
}
