//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public Items()
        {
            this.Bag = new HashSet<Bag>();
        }
    
        public int item_id { get; set; }
        public string item_n { get; set; }
        public int type_id { get; set; }
        public int stat_id { get; set; }
    
        public virtual ICollection<Bag> Bag { get; set; }
        public virtual Stats Stats { get; set; }
        public virtual Types Types { get; set; }
    }
}
