//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Races
    {
        public Races()
        {
            this.Characters = new HashSet<Characters>();
        }
    
        public int race_id { get; set; }
        public string race_n { get; set; }
        public string race_inf { get; set; }
        public int col_id { get; set; }
    
        public virtual ICollection<Characters> Characters { get; set; }
        public virtual Colors Colors { get; set; }
    }
}
