//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights
    {
        public Rights()
        {
            this.Accounts = new HashSet<Accounts>();
        }
    
        public int right_id { get; set; }
        public string right_n { get; set; }
    
        public virtual ICollection<Accounts> Accounts { get; set; }
    }
}
