//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        public Stats()
        {
            this.Characters = new HashSet<Characters>();
            this.Items = new HashSet<Items>();
        }
    
        public int stat_id { get; set; }
        public int dmg { get; set; }
        public int def { get; set; }
        public int hp { get; set; }
        public int mp { get; set; }
        public string stat_n { get; set; }
    
        public virtual ICollection<Characters> Characters { get; set; }
        public virtual ICollection<Items> Items { get; set; }
    }
}
